version: "3"
services:
  octofarm:
    container_name: octofarm
    image: octofarm/octofarm:monolithic-latest
    restart: always
    ports:
      - 4000:4000
    environment:
      - MONGO=mongodb://127.0.0.1/octofarm
    volumes:
      - /home/garret/octofarm/app/logs:/app/logs
      - /home/garret/octofarm/scripts:/scripts
      - /home/garret/octofarm/data:/data
      - /home/garret/octofarm/app/images:/app/images
